name: quick_api
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.2.0

dependencies:
  cloud_firestore: ^3.2.0
  firebase_auth: ^3.4.0
  firebase_core: ^1.19.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
