name: domain_models
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.2.0

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
