name: yum_quick
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  domain_models:
    path: ./packages/domain_models
  component_library:
    path: ./packages/component_library
  repositories:
    path: ./packages/repositories
  api:
    path: ./packages/api
  screens:
    path: ./packages/screens


  # third party
  go_router: ^12.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  rxdart: ^0.27.7
  bloc_concurrency: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
