name: yum_quick
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  domain_models:
    path: ./packages/domain_models
  component_library:
    path: ./packages/component_library
  yum_quick_backend:
    path: ./packages/yum_quick_backend

  # features
  product_list:
    path: ./packages/features/product_list

  # third party
  go_router: ^12.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  rxdart: ^0.27.7
  bloc_concurrency: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
