name: cart_repository
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  domain_models:
    path: ../domain_models
  quick_api:
    path: ../quick_api

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
