name: cart_repository
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  domain_models:
    path: ../domain_models

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
