name: repositories
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

dependencies:
  domain_models:
    path: ../domain_models
  api:
    path: ../api

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
